apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: gcr.io/shopping-cart-351917/shopping-cart/user-service:v1
          ports:
            - containerPort: 8082
          env:
            - name: MARIADB_SERVER_ADDRESS
              value: jdbc:mariadb://mariadb:3306/shoppingcart
            - name: SPRING_PROFILES_ACTIVE
              value: prod